### PR TITLE
Update for ctrulib 1.0.0 / devkitarm 45

### PR DESCRIPTION
**Pull request by Shadowtrance**

### CODE REVIEW

**Comment by d0k3** [comment]
That came out of nowhere :). Did you test this and does this improve the boot rate? Or is it a crucial fix for the new CTRUlib? You also should shoot @myriachan a PR, I guess.

**Comment by Shadowtrance** [comment]
Not sure about improving boot rate but it seems needed for the new ctrulib now that the great refactor branch has been merged into the master, hence the version bump to 1.0.0 and a bunch of changes made. But i did test it and all seems good as usual. As for sending a PR, mid_kid beat me to it (well i got bored and copied from his PR haha).

**Comment by d0k3** [comment]
Alright, I'll test myself and then merge this. I guess I'll later switch back to myriachans repo (cause otherwise you will have to keep up to date :P). CTRUlib 1.0.0 will also mean I'll have to check my otehr homebrew, oh well...

**Comment by Shadowtrance** [comment]
Yeah i only noticed it when i updated last night to the new devkitarm / libctru and Emunand9 wouldn't build to test something. So i went investigating github repo's. :) Yes i was bored...

**Comment by d0k3** [comment]
Merged this. On another note, the CTRUlib update is a damn nightmare for my CTRXplorer (I can now only hope that SteveIce updates the ctrcommon library) and I'm sure it is similar for a lot of other developers.

**Comment by Shadowtrance** [comment]
I thought he wasn't doing anything with ctrcommon anymore as (i thought) he moved to making citrus or something? I may be wrong...

**Comment by d0k3** [comment]
Yup, that's the problem here. He has made some updates to it in the past, but this is just too big.

**Comment by Shadowtrance** [comment]
We may have been a little hasty in this update (or my 3ds just hates me today), but I've just done more testing / comparison between the "update for ctrulib 1.0.0" version and the previous.
In the changed version, I can't get D9 to boot at all, always met with a black screen no matter the voodoo setting. Previous version, well i just booted it twice in a row just now no issue.
I tested this shit the other day too...argh! Guess i should test even more in future. :(
So at the moment I'm thinking updating to ctrulib 1.0.0 isn't the best idea or something has been missed somewhere...

**Comment by d0k3** [comment]
Dammit that was a pain in the ass to update... :/

I have an idea, though, and maybe you can try it (can't test it today). In firm_reboot(), the new GFXInitDefault() and the whole block of new code below - could you remove that and see if it works?

Also, second idea... It is very likely that this is just the output. This can be tested by pressing START and seeing if it reboots.

**Comment by Shadowtrance** [comment]
I think you found the issue!
Tried your first idea, boots straight away, graphics loads etc as it should.
Just commented that section out, built, booted. Done.

**Pull request merged**
